use mydb;

INSERT INTO Estoque (idEstoque, Local) 
VALUES
(1, 'Ala A - Prateleira 1'),
(2, 'Ala A - Prateleira 2'),
(3, 'Ala B - Prateleira 3'),
(4, 'Ala B - Prateleira 4'),
(5, 'Ala C - Prateleira 1'),
(6, 'Ala C - Prateleira 2'),
(7, 'Ala D - Prateleira 3'),
(8, 'Ala D - Prateleira 4'),
(9, 'Ala E - Prateleira 1'),
(10, 'Ala E - Prateleira 2'),
(11, 'Ala F - Prateleira 3'),
(12, 'Ala F - Prateleira 4'),
(13, 'Ala G - Prateleira 1'),
(14, 'Ala G - Prateleira 2'),
(15, 'Ala H - Prateleira 3'),
(16, 'Ala H - Prateleira 4'),
(17, 'Ala I - Prateleira 1'),
(18, 'Ala I - Prateleira 2'),
(19, 'Ala J - Prateleira 3'),
(20, 'Ala J - Prateleira 4'),
(21, 'Ala K - Prateleira 1'),
(22, 'Ala K - Prateleira 2'),
(23, 'Ala L - Prateleira 3'),
(24, 'Ala L - Prateleira 4'),
(25, 'Ala M - Prateleira 1'),
(26, 'Ala M - Prateleira 2'),
(27, 'Ala N - Prateleira 3'),
(28, 'Ala N - Prateleira 4'),
(29, 'Ala O - Prateleira 1'),
(30, 'Ala O - Prateleira 2'),
(31, 'Ala P - Prateleira 3'),
(32, 'Ala P - Prateleira 4'),
(33, 'Ala Q - Prateleira 1'),
(34, 'Ala Q - Prateleira 2'),
(35, 'Ala R - Prateleira 3'),
(36, 'Ala R - Prateleira 4'),
(37, 'Ala S - Prateleira 1'),
(38, 'Ala S - Prateleira 2'),
(39, 'Ala T - Prateleira 3'),
(40, 'Ala T - Prateleira 4');

select * from estoque;