USE mydb;

INSERT INTO Pagamento (idPagamento, idClientes, TipoPagamento, Detalhes, Cliente_idCliente)
VALUES
(1, 1, 'Cartão de Crédito', 'Pagamento realizado com cartão Visa', 1),
(2, 2, 'Boleto', 'Pagamento realizado via boleto bancário', 2),
(3, 3, 'Pix', 'Transferência via Pix para conta do cliente', 3),
(4, 4, 'Cartão de Crédito', 'Pagamento realizado com cartão MasterCard', 4),
(5, 5, 'Boleto', 'Boleto bancário emitido para pagamento', 5),
(6, 6, 'Pix', 'Pagamento Pix com desconto aplicado', 6),
(7, 7, 'Cartão de Crédito', 'Cartão American Express utilizado', 7),
(8, 8, 'Boleto', 'Pagamento via boleto - vencimento 10 dias', 8),
(9, 9, 'Pix', 'Transferência Pix realizada com sucesso', 9),
(10, 10, 'Cartão de Crédito', 'Pagamento com cartão Visa final 1234', 10),
(11, 11, 'Boleto', 'Boleto bancário emitido pelo sistema', 11),
(12, 12, 'Pix', 'Transferência Pix instantânea', 12),
(13, 13, 'Cartão de Crédito', 'Pagamento realizado com cartão MasterCard', 13),
(14, 14, 'Boleto', 'Boleto emitido para pagamento', 14),
(15, 15, 'Pix', 'Pagamento Pix com identificação de cliente', 15),
(16, 16, 'Cartão de Crédito', 'Cartão Visa utilizado para pagamento', 16),
(17, 17, 'Boleto', 'Boleto emitido para cliente corporativo', 17),
(18, 18, 'Pix', 'Pagamento via Pix realizado rapidamente', 18),
(19, 19, 'Cartão de Crédito', 'Pagamento com cartão MasterCard final 5678', 19),
(20, 20, 'Boleto', 'Boleto com vencimento estendido', 20),
(21, 21, 'Pix', 'Pix realizado para conta bancária do cliente', 21),
(22, 22, 'Cartão de Crédito', 'Pagamento com American Express final 4321', 22),
(23, 23, 'Boleto', 'Boleto gerado pelo sistema', 23),
(24, 24, 'Pix', 'Pix realizado com desconto para cliente especial', 24),
(25, 25, 'Cartão de Crédito', 'Cartão MasterCard utilizado', 25),
(26, 26, 'Boleto', 'Boleto bancário com vencimento rápido', 26),
(27, 27, 'Pix', 'Pagamento Pix identificado', 27),
(28, 28, 'Cartão de Crédito', 'Cartão Visa para pagamento automático', 28),
(29, 29, 'Boleto', 'Boleto para pagamento no prazo', 29),
(30, 30, 'Pix', 'Pix com confirmação imediata', 30),
(31, 31, 'Cartão de Crédito', 'Pagamento com Visa final 3456', 31),
(32, 32, 'Boleto', 'Boleto emitido para cliente recorrente', 32),
(33, 33, 'Pix', 'Transferência Pix bem-sucedida', 33),
(34, 34, 'Cartão de Crédito', 'Pagamento com MasterCard final 7890', 34),
(35, 35, 'Boleto', 'Boleto emitido para pagamento mensal', 35),
(36, 36, 'Pix', 'Pix para pagamento de fatura', 36),
(37, 37, 'Cartão de Crédito', 'American Express utilizado para pagamento', 37),
(38, 38, 'Boleto', 'Boleto emitido para pagamento a vista', 38),
(39, 39, 'Pix', 'Pagamento realizado via Pix com sucesso', 39),
(40, 40, 'Cartão de Crédito', 'Pagamento via Visa com taxa reduzida', 40);

select * from pagamento;