use mydb;

INSERT INTO Terceiro_Vendedor (idTerceiro_Vendedor, Nome_Vendedor, outros_campos) 
VALUES
(1, 'Vendedor Alpha Ltda', 'São Paulo'),
(2, 'Vendedor Beta Ltda', 'Rio de Janeiro'),
(3, 'Vendedor Gamma Comércio', 'Belo Horizonte'),
(4, 'Vendedor Delta Indústrias', 'Curitiba'),
(5, 'Vendedor Epsilon Ltda', 'Porto Alegre'),
(6, 'Vendedor Zeta Construções', 'Salvador'),
(7, 'Vendedor Omega Engenharia', 'Recife'),
(8, 'Vendedor Sigma Logística', 'Fortaleza'),
(9, 'Vendedor Kappa Serviços', 'Brasília'),
(10, 'Vendedor Lambda Soluções', 'Manaus'),
(11, 'Vendedor Pi Consultoria', 'São Paulo'),
(12, 'Vendedor Theta Comércio', 'Rio de Janeiro'),
(13, 'Vendedor Iota Indústrias', 'Belo Horizonte'),
(14, 'Vendedor Omicron Distribuidora', 'Curitiba'),
(15, 'Vendedor Alpha e Beta Ltda', 'Porto Alegre'),
(16, 'Vendedor Rho Serviços Técnicos', 'Salvador'),
(17, 'Vendedor Tau Informática', 'Recife'),
(18, 'Vendedor Upsilon Marketing', 'Fortaleza'),
(19, 'Vendedor Phi Transportes', 'Brasília'),
(20, 'Vendedor Chi Produções', 'Manaus'),
(21, 'Vendedor Psi Varejo', 'São Paulo'),
(22, 'Vendedor Omega Soluções Ltda', 'Rio de Janeiro'),
(23, 'Vendedor Gamma Importação', 'Belo Horizonte'),
(24, 'Vendedor Delta Segurança', 'Curitiba'),
(25, 'Vendedor Sigma Tech', 'Porto Alegre'),
(26, 'Vendedor Zeta Alimentos', 'Salvador'),
(27, 'Vendedor Epsilon Imóveis', 'Recife'),
(28, 'Vendedor Kappa Eventos', 'Fortaleza'),
(29, 'Vendedor Lambda Turismo', 'Brasília'),
(30, 'Vendedor Iota Veículos', 'Manaus'),
(31, 'Vendedor Theta Saúde', 'São Paulo'),
(32, 'Vendedor Pi Telecom', 'Rio de Janeiro'),
(33, 'Vendedor Phi Ambiental', 'Belo Horizonte'),
(34, 'Vendedor Chi Produtos', 'Curitiba'),
(35, 'Vendedor Rho Construções Ltda', 'Porto Alegre'),
(36, 'Vendedor Sigma Tecnologia', 'Salvador'),
(37, 'Vendedor Delta Consultoria', 'Recife'),
(38, 'Vendedor Epsilon TI', 'Fortaleza'),
(39, 'Vendedor Omega Saúde Ltda', 'Brasília'),
(40, 'Vendedor Kappa Produtos', 'Manaus');

select * from terceiro_vendedor;